import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "DigitalCraft Agency | Full Stack Web Development & E-commerce Solutions",
  description: "Leading digital agency specializing in custom web development, Shopify stores, and scalable e-commerce solutions. We transform ideas into powerful digital experiences that drive business growth.",
  keywords: [
    "digital-agency",
    "web-development",
    "ecommerce-development",
    "shopify-development",
    "custom-websites",
    "react-development",
    "nextjs-agency",
    "portfolio",
    "fullstack-development",
    "shopify-expert",
    "shopify-plus",
    "ecommerce-solutions",
    "business-websites",
    "ui-ux-design",
    "mobile-responsive",
    "seo-optimization",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "php",
    "nodejs",
    "mysql",
    "mongodb",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "DigitalCraft Agency",
    url: "https://github.com/Altamashshk",
  },
} as const;
