import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Altamas Husain | Full Stack Developer & Shopify Expert",
  description: "Full Stack Developer & Shopify Specialist with experience building and customizing e-commerce stores using Shopify, PHP, JavaScript, and MySQL. Skilled in building scalable applications with modern frontend and backend technologies.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "fullstack-developer",
    "shopify-expert",
    "shopify-developer",
    "ecommerce",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "php",
    "nodejs",
    "mysql",
    "mongodb",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Altamas Husain",
    url: "https://github.com/Altamashshk",
  },
} as const;
