import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Alex Forged | Custom Web Development & E-commerce Solutions",
  description: "Alex Forged specializes in crafting exceptional digital experiences through custom web development, e-commerce solutions, and modern UI/UX design. Forging digital excellence for businesses worldwide.",
  keywords: [
    "alex-forged",
    "custom-web-development",
    "ecommerce-development",
    "shopify-development",
    "ui-ux-design",
    "digital-solutions",
    "web-designer",
    "freelance-developer",
    "react-developer",
    "nextjs-developer",
    "portfolio",
    "web-development-services",
    "shopify-expert",
    "ecommerce-solutions",
    "responsive-design",
    "mobile-first-design",
    "performance-optimization",
    "seo-optimization",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "nodejs",
    "mysql",
    "mongodb",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Alex Forged",
    url: "https://github.com/Altamashshk",
  },
} as const;
